name: Trigger auto deployment for ep-test-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'apps/api/**'
    - '.github/workflows/ep-test-backend-AutoDeployTrigger-79680100-8576-44d6-bf61-7bb846958a78.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EPTESTBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EPTESTBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EPTESTBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/apps/api 
          registryUrl: https://ghcr.io
          registryUsername: ${{ secrets.EPTESTBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EPTESTBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ep-test-backend
          resourceGroup: ep-test
          imageToBuild: https://ghcr.io/ep-test-backend:${{ github.sha }}
          dockerfilePath: Dockerfile


